import bcrypt from 'bcryptjs';
// bcrypt.hashSync is a function to transfer password to hash and second value which is 8 is to make an auto salt 
const data = {
    users:[
        {
            name: "Ali",
            email: "admin@example.com",
            password: bcrypt.hashSync('1234',8),
            isAdmin: true,
        },
        {
            name: "amin",
            email: "user@example.com",
            password: bcrypt.hashSync('1234',8),
            isAdmin: false,
        }
    ],
    products: [
        {
            _id: 1,
            name: 'Jumpsuit',
            category: 'Fashion',
            image: '/images/jumpB2.webp',
            price: 120,
            countInStock: 10,
            brand: 'GUCCI',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: 2,
            name: 'Watch',
            category: 'Electronic',
            image: '/images/flash-4.webp',
            price: 100,
            countInStock: 20,
            brand: 'APPLE',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: 3,
            name: 'Tv',
            category: ' Electronic',
            image: '/images/discount-2.webp',
            price: 220,
            countInStock: 1,
            brand: 'SUMSUNG',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: 4,
            name: 'glasses',
            category: 'fashion',
            image: '/images/flash-5.webp',
            price: 78,
            countInStock: 15,
            brand: 'GUCCI',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: 5,
            name: 'shoes',
            category: 'fashion',
            image: '/images/flash-1.webp',
            price: 65,
            countInStock: 5,
            brand: 'Puma',
            rating: 5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: 6,
            name: 'iphon',
            category: 'Electronic',
            image: '/images/flash-3.webp',
            price: 139,
            countInStock: 12,
            brand: 'IPHONE',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
    ],
}; 

export default data;