export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'



export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'


export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_ONE_REQUEST = 'PRODUCT_ONE_REQUEST'
export const PRODUCT_ONE_SUCCESS = 'PRODUCT_ONE_SUCCESS'
export const PRODUCT_ONE_FAIL = 'PRODUCT_ONE_FAIL'

export const PRODUCT_CATEGORY_LIST_REQUEST = 'PRODUCT_CATEGORY_LIST_REQUEST';
export const PRODUCT_CATEGORY_LIST_SUCCESS = 'PRODUCT_CATEGORY_LIST_SUCCESS';
export const PRODUCT_CATEGORY_LIST_FAIL = 'PRODUCT_CATEGORY_LIST_FAIL';

export const WISHLIST_LIST_REQUEST = 'WISHLIST_LIST_REQUEST'
export const WISHLIST_LIST_SUCCESS = 'WISHLIST_LIST_SUCCESS'
export const WISHLIST_LIST_FAIL = 'WISHLIST_LIST_FAIL'

export const  WISHLIST_DELETE_REQUEST = 'WISHLIST_DELETE_REQUEST'
export const  WISHLIST_DELETE_SUCCESS = 'WISHLIST_DELETE_SUCCESS'
export const  WISHLIST_DELETE_FAIL = ' WISHLIST_DELETE_FAIL'

export const WISHLIST_DETAILS_REQUEST = 'WISHLIST_DETAILS_REQUEST'
export const WISHLIST_DETAILS_SUCCESS = 'WISHLIST_DETAILS_SUCCESS'
export const WISHLIST_DETAILS_FAIL = 'WISHLIST_DETAILS_FAIL'