export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'



export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'


export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_ONE_REQUEST = 'PRODUCT_ONE_REQUEST'
export const PRODUCT_ONE_SUCCESS = 'PRODUCT_ONE_SUCCESS'
export const PRODUCT_ONE_FAIL = 'PRODUCT_ONE_FAIL'

export const PRODUCT_CATEGORY_LIST_REQUEST = 'PRODUCT_CATEGORY_LIST_REQUEST';
export const PRODUCT_CATEGORY_LIST_SUCCESS = 'PRODUCT_CATEGORY_LIST_SUCCESS';
export const PRODUCT_CATEGORY_LIST_FAIL = 'PRODUCT_CATEGORY_LIST_FAIL';


export const PRODUCT_REVIEW_CREATE_REQUEST = 'PRODUCT_REVIEW_CREATE_REQUEST';
export const PRODUCT_REVIEW_CREATE_SUCCESS = 'PRODUCT_REVIEW_CREATE_SUCCESS';
export const PRODUCT_REVIEW_CREATE_FAIL = 'PRODUCT_REVIEW_CREATE_FAIL';
export const PRODUCT_REVIEW_CREATE_RESET = 'PRODUCT_REVIEW_CREATE_RESET';


export const  WISHLIST_ADD_REQUEST = 'WISHLIST_ADD_REQUEST';
export const  WISHLIST_ADD_SUCCESS = 'WISHLIST_ADD_SUCCESS';
export const  WISHLIST_ADD_FAIL = 'WISHLIST_ADD_FAIL';

export const  WISHLIST_ADD_ITEM = 'WISHLIST_ADD_ITEM';

export const WISHLIST_GET_REQUEST = 'WISHLIST_GET_REQUEST';
export const WISHLIST_GET_SUCCESS = 'WISHLIST_GET_SUCCESS';
export const WISHLIST_GET_FAIL = 'WISHLIST_GET_FAIL';

